#!/bin/bash

# ============================================================================
# Build Semantic View SQL from YAML
# ============================================================================
# Usage: ./build_semantic_view.sh <yaml_file> <output_sql>
# Example: ./build_semantic_view.sh semantic_views/01a_og_project_risk.yaml sql/16_semantic_view_01a.sql
# ============================================================================

if [ $# -ne 2 ]; then
    echo "Usage: $0 <yaml_file> <output_sql>"
    echo "Example: $0 semantic_views/01a_og_project_risk.yaml sql/16_semantic_view_01a.sql"
    exit 1
fi

YAML_FILE="$1"
OUTPUT_SQL="$2"

if [ ! -f "$YAML_FILE" ]; then
    echo "Error: YAML file '$YAML_FILE' not found"
    exit 1
fi

# Extract semantic view name from YAML
SV_NAME=$(grep "^name:" "$YAML_FILE" | head -1 | sed 's/name: *//')

echo "Building semantic view SQL for: $SV_NAME"
echo "  Input:  $YAML_FILE"
echo "  Output: $OUTPUT_SQL"

# Create the SQL file
echo "-- ============================================================================" > "$OUTPUT_SQL"
echo "-- Semantic View: $SV_NAME" >> "$OUTPUT_SQL"
echo "-- ============================================================================" >> "$OUTPUT_SQL"
echo "-- Auto-generated from $YAML_FILE" >> "$OUTPUT_SQL"
echo "-- DO NOT EDIT THIS FILE DIRECTLY - Edit the YAML file instead" >> "$OUTPUT_SQL"
echo "-- ============================================================================" >> "$OUTPUT_SQL"
echo "" >> "$OUTPUT_SQL"
echo "USE ROLE ACCOUNTADMIN;" >> "$OUTPUT_SQL"
echo "USE DATABASE ENERGY_WEATHER_EVENT;" >> "$OUTPUT_SQL"
echo "USE SCHEMA ENERGY_DATA;" >> "$OUTPUT_SQL"
echo "" >> "$OUTPUT_SQL"
echo "CALL SYSTEM\$CREATE_SEMANTIC_VIEW_FROM_YAML(" >> "$OUTPUT_SQL"
echo "  'ENERGY_WEATHER_EVENT.ENERGY_DATA'," >> "$OUTPUT_SQL"
echo '$$' >> "$OUTPUT_SQL"

# Append the YAML content
cat "$YAML_FILE" >> "$OUTPUT_SQL"

# Close the SQL statement
echo '' >> "$OUTPUT_SQL"
echo '$$' >> "$OUTPUT_SQL"
echo ');' >> "$OUTPUT_SQL"
echo "" >> "$OUTPUT_SQL"
echo "-- Verify semantic view created" >> "$OUTPUT_SQL"
echo "SHOW VIEWS LIKE '$SV_NAME' IN SCHEMA ENERGY_WEATHER_EVENT.ENERGY_DATA;" >> "$OUTPUT_SQL"

echo "✓ Created $OUTPUT_SQL"

