-- ============================================================================
-- Load Scenario 03 Fact Data (Hedge Mismatch Early Warning)
-- ============================================================================
-- Purpose: Generate ETRM positions, forecasts, curves, and mismatch analysis
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE ENERGY_WEATHER_EVENT;
USE SCHEMA ENERGY_DATA;
USE WAREHOUSE ENERGY_WEATHER_EVENT_WH;

-- ============================================================================
-- Generate FCT_CURVE_DATA (Monthly forward curves for 2024-2025)
-- ============================================================================
INSERT INTO FCT_CURVE_DATA (
    CURVE_DATA_KEY, CURVE_KEY, DELIVERY_TIME_KEY, SNAPSHOT_TIME_KEY,
    PRICE, VOLATILITY, BID, ASK, CONTANGO_BACKWARDATION,
    SNAPSHOT_TIMESTAMP
)
WITH curve_sim AS (
    SELECT
        c.CURVE_KEY,
        c.CURVE_NAME,
        c.COMMODITY,
        del_time.TIME_KEY AS DELIVERY_TIME_KEY,
        del_time.FULL_DATE AS DELIVERY_DATE,
        snap_time.TIME_KEY AS SNAPSHOT_TIME_KEY,
        snap_time.FULL_DATE AS SNAPSHOT_DATE,
        -- Base prices by commodity
        CASE c.COMMODITY
            WHEN 'Crude Oil' THEN UNIFORM(68, 85, RANDOM())
            WHEN 'Natural Gas' THEN UNIFORM(2.5, 4.5, RANDOM())
        END AS BASE_PRICE,
        -- Add forward premium/discount
        DATEDIFF(month, snap_time.FULL_DATE, del_time.FULL_DATE) AS MONTHS_FORWARD
    FROM DIM_CURVE c
    CROSS JOIN DIM_TIME del_time
    CROSS JOIN DIM_TIME snap_time
    WHERE c.IS_ACTIVE = TRUE
      AND del_time.DAY_OF_MONTH = 1  -- Monthly delivery
      AND del_time.FULL_DATE BETWEEN '2024-01-01' AND '2026-06-01'
      AND snap_time.DAY_OF_WEEK = 1  -- Weekly snapshots (Monday)
      AND snap_time.FULL_DATE BETWEEN '2024-01-01' AND '2024-12-31'
      AND del_time.FULL_DATE > snap_time.FULL_DATE  -- Only forward looking
      AND DATEDIFF(month, snap_time.FULL_DATE, del_time.FULL_DATE) <= 18
)
SELECT
    ROW_NUMBER() OVER (ORDER BY CURVE_KEY, DELIVERY_TIME_KEY, SNAPSHOT_TIME_KEY) AS CURVE_DATA_KEY,
    CURVE_KEY,
    DELIVERY_TIME_KEY,
    SNAPSHOT_TIME_KEY,
    -- Price with forward curve structure
    ROUND(BASE_PRICE * (1 + (MONTHS_FORWARD * 0.002)), 2) AS PRICE,
    ROUND(UNIFORM(0.25, 0.45, RANDOM()), 4) AS VOLATILITY,
    ROUND(BASE_PRICE * (1 + (MONTHS_FORWARD * 0.002)) * 0.998, 2) AS BID,
    ROUND(BASE_PRICE * (1 + (MONTHS_FORWARD * 0.002)) * 1.002, 2) AS ASK,
    CASE WHEN MONTHS_FORWARD * 0.002 > 0 THEN 'Contango' ELSE 'Backwardation' END AS CONTANGO_BACKWARDATION,
    SNAPSHOT_DATE::TIMESTAMP_NTZ AS SNAPSHOT_TIMESTAMP
FROM curve_sim;

-- ============================================================================
-- Generate FCT_ETRM_POSITIONS (Monthly hedge positions)
-- ============================================================================
INSERT INTO FCT_ETRM_POSITIONS (
    POSITION_KEY, BOOK_KEY, INSTRUMENT_KEY, TRADE_DELIVERY_POINT_KEY,
    DELIVERY_TIME_KEY, SNAPSHOT_TIME_KEY, NOTIONAL_VOLUME, WEIGHTED_AVG_PRICE,
    POSITION_TYPE, DELTA, UNREALIZED_PNL_USD, REALIZED_PNL_USD,
    SNAPSHOT_TIMESTAMP
)
WITH position_sim AS (
    SELECT
        b.BOOK_KEY,
        b.BOOK_NAME,
        b.COMMODITY,
        -- Select appropriate instrument based on commodity
        CASE b.COMMODITY
            WHEN 'Crude Oil' THEN 1  -- WTI Future
            WHEN 'Natural Gas' THEN 3  -- NG Future
        END AS INSTRUMENT_KEY,
        del_time.TIME_KEY AS DELIVERY_TIME_KEY,
        del_time.FULL_DATE AS DELIVERY_DATE,
        snap_time.TIME_KEY AS SNAPSHOT_TIME_KEY,
        snap_time.FULL_DATE AS SNAPSHOT_DATE,
        -- Generate hedge volumes (typically negative for producer hedges)
        CASE b.COMMODITY
            WHEN 'Crude Oil' THEN UNIFORM(-50000, -10000, RANDOM())
            WHEN 'Natural Gas' THEN UNIFORM(-300000, -100000, RANDOM())
        END AS HEDGE_VOLUME,
        CASE b.COMMODITY
            WHEN 'Crude Oil' THEN UNIFORM(70, 82, RANDOM())
            WHEN 'Natural Gas' THEN UNIFORM(2.8, 4.2, RANDOM())
        END AS AVG_PRICE
    FROM DIM_TRADING_BOOK b
    CROSS JOIN DIM_TIME del_time
    CROSS JOIN DIM_TIME snap_time
    WHERE b.IS_CURRENT = TRUE
      AND del_time.DAY_OF_MONTH = 1  -- Monthly delivery
      AND del_time.FULL_DATE BETWEEN '2024-01-01' AND '2025-12-01'
      AND snap_time.DAY_OF_WEEK = 1  -- Weekly snapshots
      AND snap_time.FULL_DATE BETWEEN '2024-01-01' AND '2024-12-31'
      AND del_time.FULL_DATE > snap_time.FULL_DATE
      AND DATEDIFF(month, snap_time.FULL_DATE, del_time.FULL_DATE) <= 12
)
SELECT
    ROW_NUMBER() OVER (ORDER BY BOOK_KEY, DELIVERY_TIME_KEY, SNAPSHOT_TIME_KEY) AS POSITION_KEY,
    BOOK_KEY,
    INSTRUMENT_KEY,
    NULL AS TRADE_DELIVERY_POINT_KEY,
    DELIVERY_TIME_KEY,
    SNAPSHOT_TIME_KEY,
    ROUND(HEDGE_VOLUME, 0) AS NOTIONAL_VOLUME,
    ROUND(AVG_PRICE, 2) AS WEIGHTED_AVG_PRICE,
    'Short' AS POSITION_TYPE,
    ROUND(HEDGE_VOLUME * -1, 0) AS DELTA,
    ROUND(HEDGE_VOLUME * (AVG_PRICE - AVG_PRICE * 1.05) * -1, 2) AS UNREALIZED_PNL_USD,
    0 AS REALIZED_PNL_USD,
    SNAPSHOT_DATE::TIMESTAMP_NTZ AS SNAPSHOT_TIMESTAMP
FROM position_sim;

-- ============================================================================
-- Generate FCT_PRODUCTION_FORECAST (Monthly production forecasts)
-- ============================================================================
INSERT INTO FCT_PRODUCTION_FORECAST (
    FORECAST_KEY, ASSET_KEY, FORECAST_VERSION_KEY, DELIVERY_TIME_KEY,
    P10_VOLUME, P50_VOLUME, P90_VOLUME, DETERMINISTIC_VOLUME, VOLUME_UNIT,
    ASSUMED_UPTIME_PERCENT, ASSUMED_RATE, WEATHER_IMPACT_VOLUME,
    OUTAGE_IMPACT_VOLUME, FORECAST_CONFIDENCE, STANDARD_DEVIATION,
    FORECAST_TIMESTAMP
)
WITH forecast_sim AS (
    SELECT
        a.ASSET_KEY,
        a.ASSET_TYPE,
        a.NAMEPLATE_CAPACITY,
        a.CAPACITY_UNIT,
        fv.FORECAST_VERSION_KEY,
        fv.FORECAST_RUN_DATE,
        fv.CONFIDENCE_LEVEL,
        del_time.TIME_KEY AS DELIVERY_TIME_KEY,
        del_time.FULL_DATE AS DELIVERY_DATE,
        DATEDIFF(day, DATE_TRUNC('month', del_time.FULL_DATE), LAST_DAY(del_time.FULL_DATE)) + 1 AS DAYS_IN_MONTH,
        -- Calculate monthly production
        UNIFORM(0.75, 0.95, RANDOM()) AS UPTIME,
        UNIFORM(0.85, 0.98, RANDOM()) AS RATE_FACTOR
    FROM DIM_ASSET a
    CROSS JOIN DIM_FORECAST_VERSION fv
    CROSS JOIN DIM_TIME del_time
    WHERE a.ASSET_KEY IN (1001, 1002, 1004, 1005, 1006, 1007, 1008) -- Production assets
      AND a.IS_CURRENT = TRUE
      AND del_time.DAY_OF_MONTH = 1  -- Monthly forecast
      AND del_time.FULL_DATE BETWEEN fv.FORECAST_RUN_DATE AND DATEADD(month, 12, fv.FORECAST_RUN_DATE)
      AND fv.IS_OFFICIAL = TRUE
)
SELECT
    ROW_NUMBER() OVER (ORDER BY ASSET_KEY, FORECAST_VERSION_KEY, DELIVERY_TIME_KEY) AS FORECAST_KEY,
    ASSET_KEY,
    FORECAST_VERSION_KEY,
    DELIVERY_TIME_KEY,
    -- P10/P50/P90 volumes (convert to monthly)
    ROUND(NAMEPLATE_CAPACITY * DAYS_IN_MONTH * UPTIME * RATE_FACTOR * 0.85, 0) AS P10_VOLUME,
    ROUND(NAMEPLATE_CAPACITY * DAYS_IN_MONTH * UPTIME * RATE_FACTOR, 0) AS P50_VOLUME,
    ROUND(NAMEPLATE_CAPACITY * DAYS_IN_MONTH * UPTIME * RATE_FACTOR * 1.15, 0) AS P90_VOLUME,
    ROUND(NAMEPLATE_CAPACITY * DAYS_IN_MONTH * UPTIME * RATE_FACTOR, 0) AS DETERMINISTIC_VOLUME,
    CAPACITY_UNIT AS VOLUME_UNIT,
    ROUND(UPTIME * 100, 1) AS ASSUMED_UPTIME_PERCENT,
    ROUND(NAMEPLATE_CAPACITY * RATE_FACTOR, 1) AS ASSUMED_RATE,
    ROUND(NAMEPLATE_CAPACITY * DAYS_IN_MONTH * (1 - RATE_FACTOR) * 0.3, 0) AS WEATHER_IMPACT_VOLUME,
    ROUND(NAMEPLATE_CAPACITY * DAYS_IN_MONTH * (1 - UPTIME) * 0.5, 0) AS OUTAGE_IMPACT_VOLUME,
    CASE 
        WHEN CONFIDENCE_LEVEL = 'P50' THEN 'High'
        WHEN CONFIDENCE_LEVEL = 'P10' THEN 'Low'
        ELSE 'Medium'
    END AS FORECAST_CONFIDENCE,
    ROUND(NAMEPLATE_CAPACITY * DAYS_IN_MONTH * 0.08, 0) AS STANDARD_DEVIATION,
    FORECAST_RUN_DATE::TIMESTAMP_NTZ AS FORECAST_TIMESTAMP
FROM forecast_sim;

-- ============================================================================
-- Generate FCT_MISMATCH_RISK (Mismatch analysis results)
-- ============================================================================
INSERT INTO FCT_MISMATCH_RISK (
    MISMATCH_KEY, BOOK_KEY, DELIVERY_TIME_KEY, SIMULATION_RUN_ID,
    TRADE_DELIVERY_POINT_KEY, FORECAST_VERSION_KEY,
    HEDGED_VOLUME, P50_DELIVERABLE_VOLUME, P10_DELIVERABLE_VOLUME, P90_DELIVERABLE_VOLUME,
    MISMATCH_PROBABILITY, EXPECTED_MISMATCH_UNITS, P95_MISMATCH_UNITS,
    EXPECTED_PNL_IMPACT_USD, VAR_IMPACT_USD,
    PRIMARY_RISK_DRIVER, WEATHER_CONTRIBUTION_PERCENT, OUTAGE_CONTRIBUTION_PERCENT,
    BASIS_CONTRIBUTION_PERCENT, RISK_LEVEL, ALERT_TRIGGERED,
    SIMULATION_TIMESTAMP
)
WITH mismatch_calc AS (
    SELECT
        pos.BOOK_KEY,
        pos.DELIVERY_TIME_KEY,
        del_time.FULL_DATE AS DELIVERY_DATE,
        fv.FORECAST_VERSION_KEY,
        fv.FORECAST_RUN_DATE,
        -- Aggregate hedge positions for the book/month
        SUM(pos.NOTIONAL_VOLUME) AS TOTAL_HEDGED,
        -- Aggregate production forecasts (convert BBL/day to monthly)
        SUM(fc.P10_VOLUME) AS TOTAL_P10_PROD,
        SUM(fc.P50_VOLUME) AS TOTAL_P50_PROD,
        SUM(fc.P90_VOLUME) AS TOTAL_P90_PROD,
        -- Risk analysis
        SUM(fc.WEATHER_IMPACT_VOLUME) AS WEATHER_IMPACT,
        SUM(fc.OUTAGE_IMPACT_VOLUME) AS OUTAGE_IMPACT
    FROM FCT_ETRM_POSITIONS pos
    JOIN DIM_TIME del_time ON pos.DELIVERY_TIME_KEY = del_time.TIME_KEY
    JOIN DIM_TRADING_BOOK b ON pos.BOOK_KEY = b.BOOK_KEY
    LEFT JOIN FCT_PRODUCTION_FORECAST fc ON fc.DELIVERY_TIME_KEY = pos.DELIVERY_TIME_KEY
    LEFT JOIN DIM_FORECAST_VERSION fv ON fc.FORECAST_VERSION_KEY = fv.FORECAST_VERSION_KEY
    WHERE fv.IS_OFFICIAL = TRUE
      AND del_time.FULL_DATE BETWEEN '2024-03-01' AND '2025-06-01'
    GROUP BY pos.BOOK_KEY, pos.DELIVERY_TIME_KEY, del_time.FULL_DATE, fv.FORECAST_VERSION_KEY, fv.FORECAST_RUN_DATE
)
SELECT
    ROW_NUMBER() OVER (ORDER BY BOOK_KEY, DELIVERY_TIME_KEY) AS MISMATCH_KEY,
    BOOK_KEY,
    DELIVERY_TIME_KEY,
    'SIM_' || TO_VARCHAR(FORECAST_VERSION_KEY) || '_' || TO_VARCHAR(DELIVERY_TIME_KEY) AS SIMULATION_RUN_ID,
    NULL AS TRADE_DELIVERY_POINT_KEY,
    FORECAST_VERSION_KEY,
    ABS(TOTAL_HEDGED) AS HEDGED_VOLUME,
    TOTAL_P50_PROD AS P50_DELIVERABLE_VOLUME,
    TOTAL_P10_PROD AS P10_DELIVERABLE_VOLUME,
    TOTAL_P90_PROD AS P90_DELIVERABLE_VOLUME,
    -- Calculate mismatch probability (higher when hedge > deliverable)
    CASE 
        WHEN TOTAL_P50_PROD < ABS(TOTAL_HEDGED) THEN 
            LEAST(0.95, (ABS(TOTAL_HEDGED) - TOTAL_P50_PROD) / NULLIF(TOTAL_P50_PROD, 0))
        ELSE 0.15
    END AS MISMATCH_PROBABILITY,
    ABS(TOTAL_HEDGED) - TOTAL_P50_PROD AS EXPECTED_MISMATCH_UNITS,
    ABS(TOTAL_HEDGED) - TOTAL_P10_PROD AS P95_MISMATCH_UNITS,
    (ABS(TOTAL_HEDGED) - TOTAL_P50_PROD) * 75.0 * -1 AS EXPECTED_PNL_IMPACT_USD,
    (ABS(TOTAL_HEDGED) - TOTAL_P10_PROD) * 75.0 * -1 AS VAR_IMPACT_USD,
    CASE 
        WHEN WEATHER_IMPACT > OUTAGE_IMPACT THEN 'Weather Forecast Variance'
        WHEN OUTAGE_IMPACT > WEATHER_IMPACT THEN 'Planned/Unplanned Outages'
        ELSE 'Normal Production Variance'
    END AS PRIMARY_RISK_DRIVER,
    ROUND(WEATHER_IMPACT / NULLIF(WEATHER_IMPACT + OUTAGE_IMPACT, 0) * 100, 1) AS WEATHER_CONTRIBUTION_PERCENT,
    ROUND(OUTAGE_IMPACT / NULLIF(WEATHER_IMPACT + OUTAGE_IMPACT, 0) * 100, 1) AS OUTAGE_CONTRIBUTION_PERCENT,
    10.0 AS BASIS_CONTRIBUTION_PERCENT,
    CASE 
        WHEN ABS((ABS(TOTAL_HEDGED) - TOTAL_P50_PROD) / NULLIF(TOTAL_P50_PROD, 0)) > 0.20 THEN 'High'
        WHEN ABS((ABS(TOTAL_HEDGED) - TOTAL_P50_PROD) / NULLIF(TOTAL_P50_PROD, 0)) > 0.10 THEN 'Medium'
        ELSE 'Low'
    END AS RISK_LEVEL,
    CASE 
        WHEN ABS((ABS(TOTAL_HEDGED) - TOTAL_P50_PROD) / NULLIF(TOTAL_P50_PROD, 0)) > 0.20 THEN TRUE
        ELSE FALSE
    END AS ALERT_TRIGGERED,
    FORECAST_RUN_DATE::TIMESTAMP_NTZ AS SIMULATION_TIMESTAMP
FROM mismatch_calc
WHERE TOTAL_P50_PROD IS NOT NULL;

-- Add some specific high-risk scenarios for demo
UPDATE FCT_MISMATCH_RISK
SET 
    MISMATCH_PROBABILITY = 0.75,
    RISK_LEVEL = 'High',
    ALERT_TRIGGERED = TRUE,
    PRIMARY_RISK_DRIVER = 'Hurricane Impact on Production'
WHERE DELIVERY_TIME_KEY IN (SELECT TIME_KEY FROM DIM_TIME WHERE FULL_DATE = '2024-10-01')
  AND BOOK_KEY IN (1, 4);  -- Permian and Gulf Coast books

UPDATE FCT_MISMATCH_RISK
SET 
    MISMATCH_PROBABILITY = 0.65,
    RISK_LEVEL = 'High',
    ALERT_TRIGGERED = TRUE,
    PRIMARY_RISK_DRIVER = 'Winter Freeze Impact on Wells'
WHERE DELIVERY_TIME_KEY IN (SELECT TIME_KEY FROM DIM_TIME WHERE FULL_DATE = '2025-02-01')
  AND BOOK_KEY = 5;  -- Bakken book

